#ifndef SFENGINE_RETURN_VALUES_H
#define SFENGINE_RETURN_VALUES_H


namespace Engine
{
  enum Error
  {
    INIT_NO_SFML = 1
    , INIT_CONTEXT_CREATION
    , GL_CORE_MAJOR
    , GL_CORE_MINOR
    , GL_NO_SHADERS
    , GL_BAD_EXTENSION
    , GL_SHADER_COMPILE
    , GL_INVALID_CONTEXT
    , THREAD_WORKER
    , THREAD_WORKER_UNRESPONSIVE
    , THREAD_WORKER_STARVED
    , THREAD_LOGGER
    , THREAD_LOGGER_UNRESPONSIVE
    , THREAD_LOGGER_STARVED
    , THREAD_RENDERER
    , THREAD_RENDERER_UNRESPONSIVE
    , THREAD_RENDERER_STARVED
    , RUNTIME_NULLPTR
    , RUNTIME_ENGINE_NOCURRENGINE
    , RUNTIME_ENGINE_NOCURRWINDOW
    , RUNTIME_MEMORY_ALLOC
    , RUNTIME_UNKNOWN_ERROR
    ,
  };

  enum Warning
  {
    GL_NO_AA = Error::RUNTIME_UNKNOWN_ERROR + 1
    ,
  };

  enum Success
  {
      GAMELOOP_SUCCESS = 0
    , INIT_SUCCESS
    , STARTUP_SUCCESS
    , RENDER_SUCCESS

    ,
  };
}


#endif
